/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Examen222;
import Examen222.Operaciones;
import javax.swing.JOptionPane;
/**
 *
 * @author ser1b
 */
public class Interfaz extends javax.swing.JFrame {

    private Operaciones oper;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSumarFilas = new javax.swing.JButton();
        btnTotalSucursal = new javax.swing.JButton();
        btnArticulo3 = new javax.swing.JButton();
        btnRecaudacion = new javax.swing.JButton();
        btnTotalEmpresa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSumarFilas.setText("LLenar matriz");
        btnSumarFilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarFilasActionPerformed(evt);
            }
        });

        btnTotalSucursal.setText("Total en cada sucursal");
        btnTotalSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalSucursalActionPerformed(evt);
            }
        });

        btnArticulo3.setText("Articulo 3");
        btnArticulo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticulo3ActionPerformed(evt);
            }
        });

        btnRecaudacion.setText("Recaudacion");
        btnRecaudacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecaudacionActionPerformed(evt);
            }
        });

        btnTotalEmpresa.setText("Total toda la empresa");
        btnTotalEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalEmpresaActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jButton1.setText("Total cada articulo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSumarFilas)
                        .addContainerGap(387, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTotalSucursal)
                            .addComponent(btnTotalEmpresa)
                            .addComponent(btnRecaudacion)
                            .addComponent(btnArticulo3)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btnSumarFilas)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTotalSucursal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTotalEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecaudacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnArticulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumarFilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarFilasActionPerformed
        // TODO add your handling code here:
        int filas1 = Integer.parseInt(JOptionPane.showInputDialog("Numero de filas de la primera matriz: "));
        int columnas1 = Integer.parseInt(JOptionPane.showInputDialog("Numero de columnas de la primera matriz: "));
        oper = new Operaciones(filas1, columnas1);
        int[][] datos1 = new int[filas1][columnas1];
        for (int i = 0; i < filas1; i++) {
            for (int j = 0; j < columnas1; j++) {
                datos1[i][j] = Integer.parseInt(JOptionPane.showInputDialog("Dato: [" + i + "][" + j + "]:"));
            }
        }
        oper.llenarMatriz(datos1);
    }//GEN-LAST:event_btnSumarFilasActionPerformed

    private void btnTotalSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalSucursalActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(oper.imprimirSumaFilas());
    }//GEN-LAST:event_btnTotalSucursalActionPerformed

    private void btnTotalEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalEmpresaActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(oper.imprimirSumaMatriz());
    }//GEN-LAST:event_btnTotalEmpresaActionPerformed

    private void btnArticulo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulo3ActionPerformed
        // TODO add your handling code here:
        
        int suma= oper.cantidadArticuloSucursal(3, 1);
        txtResultado.setText(""+suma);
    }//GEN-LAST:event_btnArticulo3ActionPerformed

    private void btnRecaudacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecaudacionActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(oper.imprimirRecaudacion());
    }//GEN-LAST:event_btnRecaudacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(oper.imrpimirSumaColumnas());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticulo3;
    private javax.swing.JButton btnRecaudacion;
    private javax.swing.JButton btnSumarFilas;
    private javax.swing.JButton btnTotalEmpresa;
    private javax.swing.JButton btnTotalSucursal;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
