---********************************************************
---**        ENCRIPTAR Y DESENCRIPTAR CONTRASEÑAS        **
---********************************************************
USE empresa
GO

CREATE TABLE USUARIOS
(
USUARIO VARCHAR(30) PRIMARY KEY,
PASSWORD_SIN_ENCRIPTAR VARCHAR(255),
PASSWORD_ENCRIPTADO VARBINARY(255)
)

---********************************************************
---**        ENCRIPTAR POR FRASE                         **
---********************************************************
INSERT INTO USUARIOS VALUES
('ANDRES','UTTANDRES',ENCRYPTBYPASSPHRASE('PASSWORD','UTTANDRES'))
INSERT INTO USUARIOS VALUES
('BEATRIZ','UTTBEATRIZ',ENCRYPTBYPASSPHRASE('PASSWORD','UTTBEATRIZ'))
INSERT INTO USUARIOS VALUES
('CARLOS','UTTCARLOS',ENCRYPTBYPASSPHRASE('PASSWORD','UTTCARLOS'))
INSERT INTO USUARIOS VALUES
('DANIELA','UTTDANIELA',ENCRYPTBYPASSPHRASE('PASSWORD','UTTDANIELA'))
INSERT INTO USUARIOS VALUES
('ERNESTINA','UTTERNESTINA',ENCRYPTBYPASSPHRASE('PASSWORD','UTTERNESTINA'))

INSERT INTO USUARIOS VALUES
('FELIPE','UTTFELIPE',ENCRYPTBYPASSPHRASE('PASSWORD1','UTTFELIPE'))
INSERT INTO USUARIOS VALUES
('GERARDO','UTTGERARDO',ENCRYPTBYPASSPHRASE('PASSWORD1','UTTGERARDO'))

INSERT INTO USUARIOS VALUES
('HUGO','UTTHUGO',ENCRYPTBYPASSPHRASE('PASSWORD2','UTTHUGO'))
INSERT INTO USUARIOS VALUES
('IRMA','UTTIRMA',ENCRYPTBYPASSPHRASE('PASSWORD2','UTTIRMA'))

---********************************************************
---**        DESENCRIPTAR POR FRASE                      **
---********************************************************
SELECT USUARIO,PASSWORD_SIN_ENCRIPTAR,
		CONVERT(VARCHAR(255), DECRYPTBYPASSPHRASE('PASSWORD',PASSWORD_ENCRIPTADO))
FROM USUARIOS

SELECT USUARIO,PASSWORD_SIN_ENCRIPTAR,
		CONVERT(VARCHAR(255), DECRYPTBYPASSPHRASE('PASSWORD1',PASSWORD_ENCRIPTADO))
FROM USUARIOS

SELECT USUARIO,PASSWORD_SIN_ENCRIPTAR,
		CONVERT(VARCHAR(255), DECRYPTBYPASSPHRASE('PASSWORD2',PASSWORD_ENCRIPTADO))
FROM USUARIOS

select*from usuarios;