/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.mx.uttt.interfaces;

import javax.swing.JOptionPane;
import edu.mx.uttt.Arreglos.OperMatrizes;

/**
 *
 * @author perez
 */
public class MtrizesOperaciones extends javax.swing.JFrame {

    private OperMatrizes ctrl;
    private OperMatrizes ctrl2;

    /**
     * Creates new form MtrizesOperaciones
     */
    public MtrizesOperaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFilas = new javax.swing.JTextField();
        txtColumnas = new javax.swing.JTextField();
        btnCrearM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMatriz = new javax.swing.JTextArea();
        btnMatrisT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCrarMtzs = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnSumaDI = new javax.swing.JButton();
        btnMedia = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnSumaD = new javax.swing.JButton();
        btnMediana = new javax.swing.JButton();
        btnModa = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnDesvuiacionE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResus = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Matriz", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setText("Filas:");

        jLabel2.setText("Columnas:");

        btnCrearM.setText("Crear Matriz");
        btnCrearM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMActionPerformed(evt);
            }
        });

        txtMatriz.setColumns(20);
        txtMatriz.setRows(5);
        jScrollPane1.setViewportView(txtMatriz);

        btnMatrisT.setText("Matriz Transpuesta");
        btnMatrisT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrisTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearM))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnMatrisT)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearM))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnMatrisT)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operaciones con Matrizes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 153, 153));

        btnCrarMtzs.setText("Crear Matrizes");
        btnCrarMtzs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrarMtzsActionPerformed(evt);
            }
        });

        btnMultiplicar.setText("Multiplicar Matrizes");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnSumaDI.setText("Suma Diagonal Inversa");
        btnSumaDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaDIActionPerformed(evt);
            }
        });

        btnMedia.setText("Media");
        btnMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaActionPerformed(evt);
            }
        });

        btnSumar.setText("Sumar Matrizes");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        btnSumaD.setText("Suma Diagonal");
        btnSumaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaDActionPerformed(evt);
            }
        });

        btnMediana.setText("Mediana");
        btnMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedianaActionPerformed(evt);
            }
        });

        btnModa.setText("Moda");
        btnModa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModaActionPerformed(evt);
            }
        });

        btnRestar.setText("Restar Matrizes");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });

        btnDesvuiacionE.setText("Desviacion Estandar");
        btnDesvuiacionE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvuiacionEActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Operaciones");

        txtResus.setColumns(20);
        txtResus.setRows(5);
        jScrollPane2.setViewportView(txtResus);

        txtMat.setColumns(20);
        txtMat.setRows(5);
        jScrollPane3.setViewportView(txtMat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDesvuiacionE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnModa)
                                            .addComponent(btnMediana))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(8, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnCrarMtzs)
                                .addGap(43, 43, 43)
                                .addComponent(btnSumar))
                            .addComponent(btnMultiplicar)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSumaD)
                            .addComponent(btnSumaDI)
                            .addComponent(btnMedia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRestar)
                        .addContainerGap(146, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrarMtzs)
                    .addComponent(btnSumar)
                    .addComponent(btnRestar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMultiplicar)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSumaD)
                            .addComponent(btnMediana))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSumaDI)
                            .addComponent(btnModa)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMedia)
                    .addComponent(btnDesvuiacionE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMActionPerformed
        // TODO add your handling code here:
        int filas = Integer.parseInt(txtFilas.getText());
        int columnas = Integer.parseInt(txtColumnas.getText());

        ctrl = new OperMatrizes(filas, columnas);

        int[][] datos = new int[filas][columnas];

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                datos[i][j] = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el valor en la posición " + i + "," + j + ":"));
            }
        }

        ctrl.llenarMatriz(datos);

        int[][] matrizResultado = ctrl.obtenerMatriz();

//        StringBuilder sb = new StringBuilder();
//        for (int i = 0; i < filas; i++) {
//            for (int j = 0; j < columnas; j++) {
//                sb.append(matrizResultado[i][j]).append("\t");
//            }
//            sb.append("\n\n");
//        }
        String cadena = "";
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                cadena += matrizResultado[i][j] + "\t";
            }
            cadena += "\n\n";
        }

        txtMatriz.setText(cadena);


    }//GEN-LAST:event_btnCrearMActionPerformed

    private void btnCrarMtzsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrarMtzsActionPerformed
        // TODO add your handling code here:
        int filas1 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de filas de la primera matriz:"));
        int columnas1 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de columnas de la primera matriz:"));

        int filas2 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de filas de la segunda matriz:"));
        int columnas2 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de columnas de la segunda matriz:"));

        if (columnas1 != filas2) {
            JOptionPane.showMessageDialog(this, "El número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz.");
            return;
        }

        ctrl = new OperMatrizes(filas1, columnas1);
        ctrl2 = new OperMatrizes(filas2, columnas2);

        int[][] datos1 = new int[filas1][columnas1];
        int[][] datos2 = new int[filas2][columnas2];

        for (int i = 0; i < filas1; i++) {
            for (int j = 0; j < columnas1; j++) {
                datos1[i][j] = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el elemento de la primera matriz en la posición " + i + "," + j + ":"));
            }
        }

        for (int i = 0; i < filas2; i++) {
            for (int j = 0; j < columnas2; j++) {
                datos2[i][j] = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el elemento de la segunda matriz en la posición " + i + "," + j + ":"));
            }
        }

        ctrl.llenarMatriz(datos1);
        ctrl2.llenarMatriz(datos2);

        int[][] matrizResultado = ctrl.obtenerMatriz();
        int[][] matrizResultado2 = ctrl2.obtenerMatriz();

        String cadena = "";
        cadena += "\nPrimera Matriz:\n";
        for (int i = 0; i < filas1; i++) {
            for (int j = 0; j < columnas1; j++) {
                cadena += matrizResultado[i][j] + "\t";
            }
            cadena += "\n\n";
        }
        cadena += "\n\n\nSegunda Matriz:\n";

        for (int i = 0; i < filas2; i++) {
            for (int j = 0; j < columnas2; j++) {
                cadena += matrizResultado2[i][j] + "\t";
            }
            cadena += "\n\n";
        }

//        StringBuilder sb = new StringBuilder();
//        sb.append("\nPrimera Matriz:\n");
//        for (int i = 0; i < filas1; i++) {
//            for (int j = 0; j < columnas1; j++) {
//                sb.append(matrizResultado[i][j]).append("\t");
//            }
//            sb.append("\n\n");
//        }
//        sb.append("\n\n\nSegunda Matriz:\n");
//        
//        for (int i = 0; i < filas2; i++) {
//            for (int j = 0; j < columnas2; j++) {
//                sb.append(matrizResultado2[i][j]).append("\t");
//            }
//            sb.append("\n\n");
//        }
        txtMat.setText(cadena);
    }//GEN-LAST:event_btnCrarMtzsActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        // TODO add your handling code here:
        ctrl.sumar(ctrl2);

        int filas = ctrl.getFilas();
        int columnas = ctrl.getColumnas();

//        StringBuilder sb = new StringBuilder();
//        for (int i = 0; i < filas; i++) {
//            for (int j = 0; j < columnas; j++) {
//                sb.append(ctrl.obtenerElemento(i, j)).append("\t");
//            }
//            sb.append("\n");
//        }
        String cadena = "";
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                cadena += ctrl.obtenerElemento(i, j) + "\t";
            }
            cadena += "\n\n";
        }

        txtResus.setText("Resultado de Suma:\n" + cadena);
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        // TODO add your handling code here:
        ctrl.restar(ctrl2);

        int filas = ctrl.getFilas();
        int columnas = ctrl.getColumnas();

//        StringBuilder sb = new StringBuilder();
//        for (int i = 0; i < filas; i++) {
//            for (int j = 0; j < columnas; j++) {
//                sb.append(ctrl.obtenerElemento(i, j)).append("\t");
//            }
//            sb.append("\n");
//        }
//        
        String cadena = "";
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                cadena += ctrl.obtenerElemento(i, j) + "\t";
            }
            cadena += "\n\n";
        }

        txtResus.setText("Resultado de Resta:\n" + cadena);
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        // TODO add your handling code here:
        if (ctrl.getColumnas() != ctrl2.getFilas()) {
            JOptionPane.showMessageDialog(this, "El número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz para multiplicarlas.");
            return;
        }

        ctrl.multiplicar(ctrl2);

        int filas = ctrl.getFilas();
        int columnas = ctrl.getColumnas();

//        StringBuilder sb = new StringBuilder();
//        for (int i = 0; i < filas; i++) {
//            for (int j = 0; j < columnas; j++) {
//                sb.append(ctrl.obtenerElemento(i, j)).append("\t");
//            }
//            sb.append("\n");
//        }
        String cadena = "";
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                cadena += ctrl.obtenerElemento(i, j) + "\t";
            }
            cadena += "\n\n";
        }

        txtResus.setText("Resultado de Multiplicacion:\n" + cadena);
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnSumaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaDActionPerformed
        // TODO add your handling code here:
        int sumaDiagonal = ctrl.sumaDiagonal();

        if (sumaDiagonal >= 0) {
            txtResus.setText("La Suma diagonal es: " + Integer.toString(sumaDiagonal));
        } else {
            txtResus.setText("La Matriz debe ser cuadrada para realizar esta accion.");
        }
    }//GEN-LAST:event_btnSumaDActionPerformed

    private void btnSumaDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaDIActionPerformed
        // TODO add your handling code here:
        int sumaDiagonalInversa = ctrl.sumaDiagonalInversa();

        if (sumaDiagonalInversa >= 0) {
            txtResus.setText("La Suma diagonal inversa es: " + Integer.toString(sumaDiagonalInversa));
        } else {
            txtResus.setText("La Matriz debe ser cuadrada para realizar esta accion.");
        }
    }//GEN-LAST:event_btnSumaDIActionPerformed

    private void btnMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaActionPerformed
        // TODO add your handling code here:
        double mediaAritmetica = ctrl.calcularMediaAritmetica();
        txtResus.setText("La media aritmetica es: " + Double.toString(mediaAritmetica));
    }//GEN-LAST:event_btnMediaActionPerformed

    private void btnMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedianaActionPerformed
        // TODO add your handling code here:
        double mediana = ctrl.calcularMediana();
        txtResus.setText("La Mediana es: " + Double.toString(mediana));
    }//GEN-LAST:event_btnMedianaActionPerformed

    private void btnModaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModaActionPerformed
        // TODO add your handling code here:
        int moda = ctrl.calcularModa();
        if (moda == -1) {
            txtResus.setText("No hay moda en la matriz.");
        } else {
            txtResus.setText("La moda es: " + Integer.toString(moda));
        }
    }//GEN-LAST:event_btnModaActionPerformed

    private void btnDesvuiacionEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvuiacionEActionPerformed
        // TODO add your handling code here:
        double desviacionEstandar = ctrl.calcularDesviacionEstandar();
        txtResus.setText("La desviacion estandar es: " + Double.toString(desviacionEstandar));
    }//GEN-LAST:event_btnDesvuiacionEActionPerformed

    private void btnMatrisTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrisTActionPerformed
        // TODO add your handling code here:
        txtResus.setText("La Matriz Transpuesta es: \n\n" + ctrl.MatrizTranspuesta());
    }//GEN-LAST:event_btnMatrisTActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrarMtzs;
    private javax.swing.JButton btnCrearM;
    private javax.swing.JButton btnDesvuiacionE;
    private javax.swing.JButton btnMatrisT;
    private javax.swing.JButton btnMedia;
    private javax.swing.JButton btnMediana;
    private javax.swing.JButton btnModa;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumaD;
    private javax.swing.JButton btnSumaDI;
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtColumnas;
    private javax.swing.JTextField txtFilas;
    private javax.swing.JTextArea txtMat;
    private javax.swing.JTextArea txtMatriz;
    private javax.swing.JTextArea txtResus;
    // End of variables declaration//GEN-END:variables
}
